steps:
- uses: actions/checkout@v2

- uses: GeoWerkstatt/create-jira-release@v1
  with:
    jira-project-key: 'TEST'
    jira-automation-webhook: ${{ secrets.JIRA_AUTOMATION_WEBHOOK }}
    build-version: v${{ env.VERSION }}
