name: Create new version tag

on:
  push:
    branches:
      - release 
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set build version number
        run: |
           echo VERSION=`git tag  | grep -E '^v[0-9]' | sort -V | tail -1` >> $GITHUB_ENV
           echo $VERSION
      
   #   - name: Create GitHub pre-release
   #     uses: marvinpinto/action-automatic-releases@latest
   #     with:
   #       repo_token: "${{ secrets.GITHUB_TOKEN }}"
   #      automatic_release_tag: v${{ env.VERSION }}
   #       prerelease: false
   #       title: ${{ env.VERSION }}
    
      - name: Version tag release in Jira
        uses: GeoWerkstatt/create-jira-release@v1
        with:
         jira-project-key: 'GI'
         jira-automation-webhook: ${{ secrets.JIRA_AUTOMATION_WEBHOOK }}
         build-version: ${{ env.VERSION }}
