name: Graphql

on:
  workflow_dispatch:

jobs:
  args-query:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Test Coverage
        shell: bash
        run: |-
              chmod +x ./github/workflows/samples/jirarelease.sh
              ./github/workflows/samples/jirarelease.sh
