name: Graphql

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  args-query:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Test Coverage
        shell: bash
        run: |-
             curl -X POST https://devopsprodemo.atlassian.net/gateway/api/graphql \
             -H "content-type : application/json" \
             -d '{"mutation useAddGenericLinkRelatedWork_addRelatedWorkMutation {\n jira {\n addRelatedWorkToVersion(input: {\n versionId: \"ari:cloud:jira:37570433-08ae-464a-b8c0-9d28c52f048a:version/activation/6c468cdf-3fb8-4dae-a543-ead783a4d810/10000\", relatedWorkId: \"dde3d6ef-360b-4f97-a547-098ec319fc05\", url: \"https://www.w3.org/Addressing/URL/url-spec.txt\", title: \"Reports\", category: \"Testing\"})}
              {
                success
                errors 
              {
                message
              }
             }}"}'

    


  
