name: Graphql

on:
  workflow_dispatch:

env:
 RESTAPI : ${{ secrets.RESTAPI }}
  

jobs:
  args-query:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Test Coverage
        shell: bash
        run: |-
              chmod +x ./.github/workflows/samples/jirarelease.sh
              ./.github/workflows/samples/jirarelease.sh
