name: Release
on:
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: "Tag name that the major or minor tag will point to"
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME }}
permissions:
  contents: write

jobs:
  update_tag:
    name: Update the major tag to include the ${{ github.event.inputs.TAG_NAME }} changes
    environment:
      name: releaseNewActionVersion
    runs-on: ubuntu-latest
    steps:
      - name: Update the ${{ env.TAG_NAME }} tag
        id: update-major-tag
        uses: actions/publish-action@v0.1.0
        with:
          source-tag: ${{ env.TAG_NAME }}
